### ISSUE TITLE
Create Game Stats Page

### ISSUE THREAD

**Issue by Nate-Louder** [EECE3093C/team-project-golden-girls#62]
### Summary

There needs to be a page for viewing odds and stats for a specific game. The mockup for this page is shown below:

![Image](https://user-images.githubusercontent.com/15697483/226734408-2a030c80-1396-4462-af98-9a97ee29c7b3.png)

It does not initially (for this issue) need to make API calls.

### Solution

Create a new GamePage component, style it to match the mockup, add a Router path to App.tsx for the component. The GamePage component should use the Odds component, Previous Games component, Players component, matchups component, and Other Stats component.

**Comment by Clicky02** [comment]
We are only creating the skeleton for now because the widget aren't ready, but we still need a place to test them
