### ISSUE TITLE
Have Game Stats Page request odds information from API

### ISSUE THREAD

**Issue by Nate-Louder** [EECE3093C/team-project-golden-girls#63]
### Summary 

The initial version of the Game Stats Page will not retrieve information from the API. However, it should be updated so that is fully functional.

### Solution 

Update APIHandler.tsx to interface with the necessary API endpoint. Then, modify the game stats page component to use APIHandler to get the necessary information.

**Comment by Clicky02** [comment]
This involved pretty heavy modification of the GameOdds Widget. Nate and I worked together on finishing this to make sure the API was sending the necessary information in the right format and that the front-end could parse it.
