### ISSUE TITLE
Restyle Front End Game Stats Page to Match Mockup

### ISSUE THREAD

**Issue by jimmygerman99** [EECE3093C/team-project-golden-girls#76]
Summary: We have decided that it is best if we update the styling from the gold coloring to a gradient

Previous: 

![Image](https://user-images.githubusercontent.com/110677113/228347639-9a3484aa-4c6d-4a29-85e2-a2c0c6712b37.png)

New: 

![Image](https://user-images.githubusercontent.com/110677113/228347681-584d9312-a6c5-44bf-9b35-7ceaade5c9a6.png)

Solution: Remove the gold stylling and change the style to a gradient in the css files

**Comment by Nate-Louder** [comment]
This should be done as widgets are created. Most commits will include the issue of the widget creation.

**Comment by Nate-Louder** [comment]
See last comment for close reasoning
